-- Bảng Nhóm người dùng
CREATE TABLE NHOM_NGUOI_DUNG (
    MaNND INT IDENTITY(1,1),
    TenNND NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_NHOM_NGUOI_DUNG PRIMARY KEY (MaNND)
);

-- Bảng Nhân viên
CREATE TABLE NHAN_VIEN (
    MaNV INT IDENTITY(1,1),
    MaNND INT NOT NULL,
    TenNV NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    SDT NVARCHAR(15) NOT NULL,
    GioiTinh NVARCHAR(10) CHECK (GioiTinh IN (N'Nam', N'Nữ')),
    ThanhPho NVARCHAR(50),
    Quan NVARCHAR(50),
    Duong NVARCHAR(50),
    SoNha NVARCHAR(20),
    CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (MaNV),
    CONSTRAINT FK_NHAN_VIEN_NHOM_NGUOI_DUNG FOREIGN KEY (MaNND) REFERENCES NHOM_NGUOI_DUNG(MaNND),
    CONSTRAINT UQ_NHAN_VIEN_SDT UNIQUE (SDT)
);

-- Bảng Đăng nhập
CREATE TABLE DANG_NHAP (
    MaNV INT NOT NULL,
    Tentaikhoan NVARCHAR(100) NOT NULL,
    Matkhau NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_DANG_NHAP PRIMARY KEY (Tentaikhoan),
    CONSTRAINT FK_DANG_NHAP_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

-- Bảng Quyền
CREATE TABLE QUYEN (
    MaQuyen INT IDENTITY(1,1),
    TenQuyen NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_QUYEN PRIMARY KEY (MaQuyen)
);

-- Bảng Phân quyền
CREATE TABLE PHANQUYEN (
    MaNND INT NOT NULL,
    MaQuyen INT NOT NULL,
    Mota NVARCHAR(200),
    CONSTRAINT PK_PHANQUYEN PRIMARY KEY (MaNND, MaQuyen),
    CONSTRAINT FK_PHANQUYEN_NHOM_NGUOI_DUNG FOREIGN KEY (MaNND) REFERENCES NHOM_NGUOI_DUNG(MaNND),
    CONSTRAINT FK_PHANQUYEN_QUYEN FOREIGN KEY (MaQuyen) REFERENCES QUYEN(MaQuyen)
);

-- Bảng Khách hàng
CREATE TABLE KHACH_HANG (
    MaKH INT IDENTITY(1,1),
    TenKH NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    SDT NVARCHAR(15) NOT NULL,
    GioiTinh NVARCHAR(10) CHECK (GioiTinh IN (N'Nam', N'Nữ')),
    ThanhPho NVARCHAR(50),
    Quan NVARCHAR(50),
    Duong NVARCHAR(50),
    SoNha NVARCHAR(20),
    CONSTRAINT PK_KHACH_HANG PRIMARY KEY (MaKH),
    CONSTRAINT UQ_KHACH_HANG_SDT UNIQUE (SDT)
);

-- Bảng Loại thẻ thành viên
CREATE TABLE LOAI_THE_THANH_VIEN (
    Maloaithe INT IDENTITY(1,1),
    Tenloaithe NVARCHAR(100) NOT NULL,
    Dieukien NVARCHAR(200),
    CONSTRAINT PK_LOAI_THE_THANH_VIEN PRIMARY KEY (Maloaithe)
);

-- Bảng Thẻ thành viên
CREATE TABLE THE_THANH_VIEN (
    Masothe INT IDENTITY(1,1),
    MaKH INT NOT NULL,
    Ngaycap DATE NOT NULL,
    Maloaithe INT  NULL,
    DiemTichLuy INT CHECK (DiemTichLuy >= 0),
    CONSTRAINT PK_THE_THANH_VIEN PRIMARY KEY (Masothe),
    CONSTRAINT FK_THE_THANH_VIEN_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    CONSTRAINT FK_THE_THANH_VIEN_LOAI_THE_THANH_VIEN FOREIGN KEY (Maloaithe) REFERENCES LOAI_THE_THANH_VIEN(Maloaithe)
);

-- Bảng Nhà cung ứng
CREATE TABLE NHA_CUNG_UNG (
    MaNCU INT IDENTITY(1,1),
    TenNCU NVARCHAR(100) NOT NULL,
    SDT NVARCHAR(15) NOT NULL,
    Email NVARCHAR(100),
    ThanhPho NVARCHAR(50),
    Quan NVARCHAR(50),
    Duong NVARCHAR(50),
    SoNha NVARCHAR(20),
    CONSTRAINT PK_NHA_CUNG_UNG PRIMARY KEY (MaNCU),
    CONSTRAINT UQ_NHA_CUNG_UNG_SDT UNIQUE (SDT),
    CONSTRAINT UQ_NHA_CUNG_UNG_EMAIL UNIQUE (Email)
);

-- Bảng Nhập hàng
CREATE TABLE NHAP (
    MaHDN INT IDENTITY(1,1),
    NgayDat DATE NOT NULL,
    TongTien DECIMAL(18,2) CHECK (TongTien >= 0),
    MaNCU INT NOT NULL,
    CONSTRAINT PK_NHAP PRIMARY KEY (MaHDN),
    CONSTRAINT FK_NHAP_NHA_CUNG_UNG FOREIGN KEY (MaNCU) REFERENCES NHA_CUNG_UNG(MaNCU)
);

-- Bảng Loại mặt hàng
CREATE TABLE LOAI_MAT_HANG (
    MaLoai INT IDENTITY(1,1),
    TenLoai NVARCHAR(100) NOT NULL,
    CongDung NVARCHAR(200),
    CONSTRAINT PK_LOAI_MAT_HANG PRIMARY KEY (MaLoai)
);

-- Bảng Mặt hàng
CREATE TABLE MAT_HANG (
    MaSP INT IDENTITY(1,1),
    MaLoai INT NOT NULL,
    TenSP NVARCHAR(100) NOT NULL,
    DonGia DECIMAL(18,2) CHECK (DonGia >= 0),
    SLTonKho INT CHECK (SLTonKho >= 0),
    MoTaChiTiet NVARCHAR(MAX),
    DonViTinh NVARCHAR(20),
    Size NVARCHAR(20),
    CONSTRAINT PK_MAT_HANG PRIMARY KEY (MaSP),
    CONSTRAINT FK_MAT_HANG_LOAI_MAT_HANG FOREIGN KEY (MaLoai) REFERENCES LOAI_MAT_HANG(MaLoai)
);

-- Bảng Chi tiết nhập
CREATE TABLE CHI_TIET_NHAP (
    MaSP INT NOT NULL,
    MaHDN INT NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    ChietKhau DECIMAL(18,2) CHECK (ChietKhau >= 0),
    VAT DECIMAL(18,2) CHECK (VAT >= 0),
    CONSTRAINT PK_CHI_TIET_NHAP PRIMARY KEY (MaSP, MaHDN),
    CONSTRAINT FK_CHI_TIET_NHAP_MAT_HANG FOREIGN KEY (MaSP) REFERENCES MAT_HANG(MaSP),
    CONSTRAINT FK_CHI_TIET_NHAP_NHAP FOREIGN KEY (MaHDN) REFERENCES NHAP(MaHDN)
);

-- Bảng Mua hàng
CREATE TABLE MUA (
    MaHD INT IDENTITY(1,1),
    NgayGiaoDich DATE NOT NULL,
    MaKH INT NOT NULL,
    TongTien DECIMAL(18,2) CHECK (TongTien >= 0),
    CONSTRAINT PK_MUA PRIMARY KEY (MaHD),
    CONSTRAINT FK_MUA_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);

-- Bảng Chi tiết mua
CREATE TABLE CHI_TIET_MUA (
    MaSP INT NOT NULL,
    MaHD INT NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    ChietKhau DECIMAL(18,2) CHECK (ChietKhau >= 0),
    VAT DECIMAL(18,2) CHECK (VAT >= 0),
    CONSTRAINT PK_CHI_TIET_MUA PRIMARY KEY (MaSP, MaHD),
    CONSTRAINT FK_CHI_TIET_MUA_MUA FOREIGN KEY (MaHD) REFERENCES MUA(MaHD),
    CONSTRAINT FK_CHI_TIET_MUA_MAT_HANG FOREIGN KEY (MaSP) REFERENCES MAT_HANG(MaSP)
);
